---
- name: Ensure directory exists for TLS certs.
  file:
    path: "{{ ssl_cert_directory }}"
    state: directory

- name: Generate an OpenSSL private key.
  openssl_privatekey:
    path: "{{ ssl_private_key_path }}"
  register: new_key

- name: Generate an OpenSSL CSR.
  openssl_csr:
    path: /root/csr.pem
    privatekey_path: "{{ ssl_private_key_path }}"
    common_name: "{{ hostname }}"
  when: new_key.changed

- name: Generate a Self Signed OpenSSL certificate.
  openssl_certificate:
    path: "{{ ssl_cert_path }}"
    privatekey_path: "{{ ssl_private_key_path }}"
    csr_path: /root/csr.pem
    provider: selfsigned
  when: new_key.changed
  notify:
  - restart nginx

- name: Delete the csr
  file:
    state: absent
    path: /root/csr.pem
